# .goreleaser.yaml
project_name: srn-music
version: 2
builds:
  - id: smusic
    main: ./
    binary: smusic
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
    goarch:
      - amd64

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: infraflakes
    name: srn-music
